version: '3'
services:
  db:
    image: rethinkdb
    ports:
      - "8080:8080"
  web:
    build: .
    command: nodemon
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
